// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace BlazeDemo.Tests
{
    [TestFixture]
    public class BlazeDemoTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;

        [SetUp]
        public void SetUp()
        {
            // Cấu hình tuỳ chỉnh: Bắt buộc giữ lại để chạy được trên GitHub Actions (CI/CD)
            var options = new ChromeOptions();
            options.AddArgument("--headless");
            options.AddArgument("--no-sandbox");
            options.AddArgument("--disable-gpu");
            options.AddArgument("--disable-dev-shm-usage");

            driver = new ChromeDriver(options);
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        }

        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
            driver.Dispose();
        }

        [Test]
        public void purchaseFlight()
        {
            // Test name: PurchaseFlight
            // Step # | name | target | value

            // 1 | open | / | 
            driver.Navigate().GoToUrl("https://blazedemo.com/");

            // 2 | setWindowSize | 1280x800 | 
            driver.Manage().Window.Size = new System.Drawing.Size(1280, 800);

            // 3 | select | name=fromPort | label=Paris
            {
                var dropdown = driver.FindElement(By.Name("fromPort"));
                dropdown.FindElement(By.XPath("//option[. = 'Paris']")).Click();
            }

            // 4 | select | name=toPort | label=London
            {
                var dropdown = driver.FindElement(By.Name("toPort"));
                dropdown.FindElement(By.XPath("//option[. = 'London']")).Click();
            }

            // 5 | click | css=.btn-primary | 
            driver.FindElement(By.CssSelector(".btn-primary")).Click();

            // 6 | click | css=tr:nth-child(1) .btn | 
            driver.FindElement(By.CssSelector("tr:nth-child(1) .btn")).Click();

            // 7 | type | id=inputName | Nguyen Van A
            driver.FindElement(By.Id("inputName")).SendKeys("Nguyen Van A");

            // 8 | type | id=address | 140 Le Trong Tan
            driver.FindElement(By.Id("address")).SendKeys("140 Le Trong Tan");

            // 9 | select | id=cardType | label=Visa
            {
                var dropdown = driver.FindElement(By.Id("cardType"));
                dropdown.FindElement(By.XPath("//option[. = 'Visa']")).Click();
            }

            // 10 | click | css=.btn-primary | 
            driver.FindElement(By.CssSelector(".btn-primary")).Click();

            // 11 | assertText | css=h1 | Thank you for your purchase today!
            Assert.That(driver.FindElement(By.CssSelector("h1")).Text, Is.EqualTo("Thank you for your purchase today!"));
        }
    }
}