name: .NET Core Test Automation Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./BlazeDemo.Tests

    steps:
    - name: 1. Checkout Source Code
      uses: actions/checkout@v4

    - name: 2. Setup .NET SDK Moi truong
      uses: actions/setup-dotnet@v4
      # Đã bỏ giới hạn phiên bản để nó tự động nhận diện .NET 10.0 của bạn

    - name: 3. Khoi phuc thu vien (Restore)
      run: dotnet restore

    - name: 4. Kich hoat Bien dich & Test Tu dong
      # Lệnh này sẽ tự động build đúng thư mục rồi test luôn, tránh mọi rủi ro
      run: dotnet test --verbosity normal